---
title: "The relationship between the population of each neighborhood and counts of break and enter in 2016."
author: "Fang Jia"
date: 2020-09-24T21:13:14-05:00
abstract: "This paper uses the dataset of neighborhood crime rates found on the Toronto Open Data Portal. We find that each neighborhood's population in 2016 is positively related to counts of break and enter in 2016. Our findings have implications for predicting crime rates by using population."
bibliography: "reference.bib"
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---



<div id="part-i-introduction" class="section level1">
<h1>Part I Introduction</h1>
<p>In this experiment, we focus on analyzing the relationship between two numerical variables. We select two interesting variables from the data we found on the Toronto Open Data Portal. Y is the counts of break and enter in 2016. X is the population of each neighborhood in 2016. We assume there is a relationship between (counts of break and enter in 2016) and each neighborhood’s population in 2016.</p>
<p>Firstly, we create a histogram of counts of break and enter in 2016. It shows the distribution, center, and spread. Secondly, we make a scatter plot of (counts of break and enter in 2016) and each neighborhood population in 2016. It tells the association between (counts of break and enter in 2016) and each neighborhood’s population in 2016. From the above graphs, we could tell whether there is a relationship between X and Y or not.</p>
<p>However, there are some limitations of data. Many factors affect counts of break and enter in 2016 beside each neighborhood’s population. If we only analyze population and counts of break and enter in 2016, we can’t tell whether the population affect counts of break and enter in 2016 or not. In future work, we need to find the recent five years of data to analyze their relationship.</p>
<p>Outline of the paper: I Introduction
- Major specific finding
- How to find the finding
- The limitation of data</p>
<pre><code>                     II Data
                     - describe data background
                     - describe data parameters 
                     
                     III Graphs
                     - create a histogram 
                     - create a boxplot
                     
                     IV Description 
                     - discuss histogram 
                     - discuss scatter plot
                     
                     V Reference 
                      
                     
                     </code></pre>
</div>
<div id="part-ii-data" class="section level1">
<h1>Part II Data</h1>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;
## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag
## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union
## # A tibble: 1 x 10
##   title id    topics civic_issues excerpt dataset_category num_resources formats
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   &lt;chr&gt;                    &lt;int&gt; &lt;chr&gt;  
## 1 Neig… fc4d… &lt;NA&gt;   &lt;NA&gt;         &lt;NA&gt;    &lt;NA&gt;                         1 &lt;NA&gt;   
## # … with 2 more variables: refresh_rate &lt;chr&gt;, last_refreshed &lt;date&gt;
## Rows: 140
## Columns: 62
## $ `_id`                   &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…
## $ OBJECTID                &lt;int&gt; 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 2…
## $ Neighbourhood           &lt;chr&gt; &quot;South Parkdale&quot;, &quot;South Riverdale&quot;, &quot;St.Andr…
## $ Hood_ID                 &lt;chr&gt; &quot;085&quot;, &quot;070&quot;, &quot;040&quot;, &quot;061&quot;, &quot;021&quot;, &quot;022&quot;, &quot;13…
## $ Population              &lt;int&gt; 21849, 27876, 17812, 15683, 12416, 15545, 133…
## $ Assault_2014            &lt;int&gt; 202, 215, 53, 127, 76, 117, 50, 480, 247, 79,…
## $ Assault_2015            &lt;int&gt; 226, 207, 41, 92, 89, 132, 39, 495, 259, 97, …
## $ Assault_2016            &lt;int&gt; 231, 236, 48, 97, 118, 114, 48, 543, 244, 106…
## $ Assault_2017            &lt;int&gt; 229, 243, 45, 107, 116, 157, 48, 694, 243, 11…
## $ Assault_2018            &lt;int&gt; 220, 304, 55, 123, 109, 119, 46, 766, 288, 13…
## $ Assault_2019            &lt;int&gt; 251, 261, 58, 122, 118, 161, 48, 879, 282, 13…
## $ Assault_AVG             &lt;dbl&gt; 226.5, 244.3, 50.0, 111.3, 104.3, 133.3, 46.5…
## $ Assault_CHG             &lt;dbl&gt; 0.14, -0.14, 0.05, -0.01, 0.08, 0.35, 0.04, 0…
## $ Assault_Rate_2019       &lt;dbl&gt; 1148.8, 936.3, 325.6, 777.9, 950.4, 1035.7, 3…
## $ AutoTheft_2014          &lt;int&gt; 13, 18, 15, 11, 66, 36, 8, 31, 42, 17, 8, 14,…
## $ AutoTheft_2015          &lt;int&gt; 20, 23, 25, 9, 42, 33, 7, 24, 29, 12, 7, 9, 1…
## $ AutoTheft_2016          &lt;int&gt; 23, 27, 10, 7, 62, 45, 5, 23, 44, 10, 4, 7, 5…
## $ AutoTheft_2017          &lt;int&gt; 19, 37, 15, 5, 83, 58, 8, 27, 40, 18, 12, 12,…
## $ AutoTheft_2018          &lt;int&gt; 17, 40, 21, 12, 106, 56, 10, 68, 46, 23, 8, 1…
## $ AutoTheft_2019          &lt;int&gt; 20, 40, 35, 12, 135, 68, 19, 54, 66, 19, 8, 1…
## $ AutoTheft_AVG           &lt;dbl&gt; 18.7, 30.8, 20.2, 9.3, 82.3, 49.3, 9.5, 37.8,…
## $ AutoTheft_CHG           &lt;dbl&gt; 0.18, 0.00, 0.67, 0.00, 0.27, 0.21, 0.90, -0.…
## $ AutoTheft_Rate_2019     &lt;dbl&gt; 91.5, 143.5, 196.5, 76.5, 1087.3, 437.4, 142.…
## $ BreakandEnter_2014      &lt;int&gt; 45, 89, 81, 31, 54, 35, 13, 141, 130, 41, 50,…
## $ BreakandEnter_2015      &lt;int&gt; 51, 98, 79, 71, 44, 35, 15, 152, 116, 58, 20,…
## $ BreakandEnter_2016      &lt;int&gt; 71, 148, 57, 43, 41, 24, 19, 145, 86, 57, 14,…
## $ BreakandEnter_2017      &lt;int&gt; 58, 94, 91, 27, 40, 21, 23, 199, 103, 36, 12,…
## $ BreakandEnter_2018      &lt;int&gt; 78, 91, 81, 41, 56, 44, 16, 191, 65, 51, 14, …
## $ BreakandEnter_2019      &lt;int&gt; 89, 133, 83, 63, 57, 61, 29, 303, 65, 46, 16,…
## $ BreakandEnter_AVG       &lt;dbl&gt; 65.3, 108.8, 78.7, 46.0, 48.7, 36.7, 19.2, 18…
## $ BreakandEnter_CHG       &lt;dbl&gt; 0.14, 0.46, 0.02, 0.54, 0.02, 0.39, 0.81, 0.5…
## $ BreakandEnter_Rate_2019 &lt;dbl&gt; 407.3, 477.1, 466.0, 401.7, 459.1, 392.4, 217…
## $ Homicide_2014           &lt;int&gt; 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, …
## $ Homicide_2015           &lt;int&gt; 0, 0, 0, 1, 1, 0, 0, 4, 2, 1, 0, 1, 0, 0, 0, …
## $ Homicide_2016           &lt;int&gt; 1, 3, 0, 1, 0, 1, 0, 3, 1, 0, 0, 0, 0, 0, 0, …
## $ Homicide_2017           &lt;int&gt; 0, 5, 2, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, …
## $ Homicide_2018           &lt;int&gt; 0, 2, 0, 0, 1, 0, 1, 2, 3, 1, 0, 0, 0, 0, 1, …
## $ Homicide_2019           &lt;int&gt; 1, 0, 0, 1, 3, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, …
## $ Homicide_AVG            &lt;dbl&gt; 0.3, 1.8, 0.5, 0.7, 1.2, 0.3, 0.3, 2.0, 1.2, …
## $ Homicide_CHG            &lt;dbl&gt; 1.00, -1.00, 0.00, 1.00, 2.00, 0.00, -1.00, -…
## $ Homicide_Rate_2019      &lt;dbl&gt; 4.6, 0.0, 0.0, 6.4, 24.2, 0.0, 0.0, 3.2, 3.7,…
## $ Robbery_2014            &lt;int&gt; 24, 64, 8, 24, 22, 28, 10, 122, 40, 28, 25, 1…
## $ Robbery_2015            &lt;int&gt; 35, 42, 5, 37, 23, 27, 4, 128, 44, 22, 22, 17…
## $ Robbery_2016            &lt;int&gt; 41, 49, 14, 16, 23, 24, 13, 114, 46, 24, 24, …
## $ Robbery_2017            &lt;int&gt; 30, 64, 0, 20, 27, 34, 11, 138, 51, 30, 20, 3…
## $ Robbery_2018            &lt;int&gt; 35, 40, 4, 16, 31, 29, 6, 169, 28, 14, 16, 21…
## $ Robbery_2019            &lt;int&gt; 33, 35, 12, 13, 28, 27, 1, 143, 37, 25, 13, 2…
## $ Robbery_AVG             &lt;dbl&gt; 33.0, 49.0, 7.2, 21.0, 25.7, 28.2, 7.5, 135.7…
## $ Robbery_CHG             &lt;dbl&gt; -0.06, -0.13, 2.00, -0.19, -0.10, -0.07, -0.8…
## $ Robbery_Rate_2019       &lt;dbl&gt; 151.0, 125.6, 67.4, 82.9, 225.5, 173.7, 7.5, …
## $ TheftOver_2014          &lt;int&gt; 6, 18, 10, 4, 15, 1, 1, 32, 4, 4, 9, 2, 1, 4,…
## $ TheftOver_2015          &lt;int&gt; 4, 16, 14, 3, 16, 9, 1, 16, 15, 5, 3, 4, 5, 2…
## $ TheftOver_2016          &lt;int&gt; 9, 22, 8, 5, 18, 1, 1, 40, 18, 3, 3, 2, 4, 4,…
## $ TheftOver_2017          &lt;int&gt; 10, 27, 7, 2, 18, 7, 4, 30, 7, 7, 4, 3, 1, 8,…
## $ TheftOver_2018          &lt;int&gt; 9, 24, 6, 4, 15, 10, 2, 43, 12, 3, 1, 5, 1, 6…
## $ TheftOver_2019          &lt;int&gt; 22, 21, 6, 3, 22, 8, 3, 42, 14, 3, 3, 6, 2, 8…
## $ TheftOver_AVG           &lt;dbl&gt; 10.0, 21.3, 8.5, 3.5, 17.3, 6.0, 2.0, 33.8, 1…
## $ TheftOver_CHG           &lt;dbl&gt; 1.44, -0.13, 0.00, -0.25, 0.47, -0.20, 0.50, …
## $ TheftOver_Rate_2019     &lt;dbl&gt; 100.7, 75.3, 33.7, 19.1, 177.2, 51.5, 22.5, 1…
## $ Shape__Area             &lt;dbl&gt; 2286974, 10964574, 7299580, 1062970, 7966905,…
## $ Shape__Length           &lt;dbl&gt; 10802.832, 43080.725, 13025.997, 5940.700, 12…
## $ geometry                &lt;POLYGON [°]&gt; POLYGON ((-79.42774 43.6297..., POLYG…</code></pre>
<p>The data set is called the Neighbourhood Crime Rates. There are a total of 62 variables and 140 observations in the data set. It includes Assault, Auto Theft, Break and Enter, Robbery, Theft Over, and Homicide for 2014-2019. It also has five-year averages and crime rates per 100,000 people by neighborhood based on the 2016 Census Population. The following chart shows the interpretation of every variable in the data set.</p>
<p>1._id : Unique row identifier for Open Data database</p>
<p>OBJECTID: Autogenerated distinct record identifier</p>
<p>Neighbourhood: Name of City of Toronto neighbourhood</p>
<p>Hood_ID: City of Toronto neighbourhood identifier</p>
<p>Population: 2016 Census Population</p>
<p>Assault_2014/Assault_2015/Assault_2016/Assault_2017/Assault_2018/Assault_2019 : Count of assaults for 2014/2015/2016/2017/2018/2019 respectively.</p>
<p>Assault_AVG:Average Assaults from 2014 - 2019</p>
<p>Assault_CHG: % Change in assaults from 2018-2019</p>
<p>Assault_Rate_2019: Rate of assaults for 2019 per 100,000 population</p>
<p>AutoTheft_2014/AutoTheft_2015/AutoTheft_2016/AutoTheft_2017/AutoTheft_2018/AutoTheft_2019: Count of auto thefts for 2014/2015/2016/2017/2018/2019 respectively.</p>
<p>AutoTheft_AVG: Averate auto thefts from 2014-2019</p>
<p>AutoTheft_CHG: % Change in auto thefts from 2018-2019</p>
<p>AutoTheft_Rate_2019: Rate of auto thefts for 2019 per 100,000 population</p>
<p>BreakandEnter_2014/BreakandEnter_2015/BreakandEnter_2016/BreakandEnter_2017/
BreakandEnter_2018/BreakandEnter_2019: Count of break and enters for
2014/2015/2016/2017/2018/2019 respectively.</p>
<p>BreakandEnter_AVG:Averate break and enters from 2014-2019</p>
<p>BreakandEnter_CHG: % Change in break and enters from 2018-2019</p>
<p>BreakandEnter_Rate_2019: Rate of break and enters for 2019 per 100,000 population</p>
<p>Homicide_2014/Homicide_2015/Homicide_2016/Homicide_2017/Homicide_2018
/Homicide_2019: Count of homicides for 2014/2015/2016/2017/2018/2019 respectively.</p>
<p>Homicide_AVG: Averate homicides from 2014-2019</p>
<p>Homicide_CHG: % Change in homicides from 2018-2019</p>
<p>Homicide_Rate_2019: Rate of homicides for 2019 per 100,000 population</p>
<p>Robbery_2014/Robbery_2015/Robbery_2016/Robbery_2017/Robbery_2018
/Robbery_2019: Count of robberies for 2014/2015/2016/2017/2018/2019 respectively.</p>
<p>Robbery_AVG: Averate robberies from 2014-2019</p>
<p>Robbery_CHG: % Change in robberies from 2018-2019</p>
<p>Robbery_Rate_2019: Rate of robberies for 2019 per 100,000 population</p>
<p>TheftOver_2014/TheftOver_2015/TheftOver_2016/TheftOver_2017
/TheftOver_2018/TheftOver_2019: Count of thefts over for
2014/2015/2016/2017/2018/2019 respectively.</p>
<p>TheftOver_AVG: Averate thefts over from 2014-2019</p>
<p>TheftOver_CHG: % Change in thefts over from 2018-2019</p>
<p>TheftOver_Rate_2019:Rate of thefts over for 2019 per 100,000 population</p>
<p>Shape__Area: Autogenerated area measurement</p>
<p>Shape__Length: Autogenerated length measurement</p>
<p>Geometry: the x and y coordinates of associated neighbourhood</p>
</div>
<div id="part-iii-graphs" class="section level1">
<h1>Part III Graphs</h1>
<pre><code>## ── Attaching packages ──────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──
## ✓ tibble  3.0.3     ✓ purrr   0.3.4
## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0
## ── Conflicts ─────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<p><img src="/post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre><code>##   counts_of_crime_median counts_of_crime_mean
## 1                     38                 45.7
## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-2-2.png" width="672" /><img src="/post/2015-07-23-r-rmarkdown_files/figure-html/unnamed-chunk-2-3.png" width="672" /></p>
</div>
<div id="part-iv-description" class="section level1">
<h1>Part IV Description</h1>
<p>The above histogram shows a non-symmetric distribution. If the distribution cut in half, the left side frequency is higher than the right side frequency.Which means more neighborhoods have less than 100 counts of break and enter. We find that the distribution of counts of break and enter for 2016 is heavily right-skewed. It is not an approximately normal distribution.</p>
<p>To describe the spread of the distribution of counts of break and enter, we calculate the standard deviation of counts of break and enter. Standard deviation represents the average distance away from the mean. Which means it shows how well the mean. The standard deviation of counts of break and enter is round 31.4212, which is larger than 0. The result tells the mean is not so representative of the data.</p>
<p>We can describe the center of the distribution of counts of break and enter by analyzing mean and median. Since the distribution of break and enter counts is not approximately normal, we can describe the center by using the median. The mean and median for the counts of break and enter are 45.7 and 38, respectively. Therefore, we can tell that the distribution of the break and enter counts is centered at 38.</p>
<p>Using the above scatter plot, we find the relationship between population and (counts of break and enter) in 2016. The dotted line shows the strong positive linear line for population and (break and enter) in 2016. When each neighborhood’s population in 2016 increased, the counts of break and enter in 2016 will also increase.</p>
<p>We made a boxplot to identify any unusual population points and (counts of break and enter) in 2016. There are six red dots beyond the two variables’ boxplot; it counts as unusual points or outliers. There is one red dot that is significantly larger than other outliers. It is larger than 200. This means that one neighborhood in Toronto has over 200 counts of break and enter. It is associated with the neighborhood of Waterfront Communities-The Island. It implies that Waterfront Communities-The Island is a dangerous place compared to other neighborhoods.</p>
</div>
<div id="reference" class="section level1">
<h1>Reference</h1>
<p>1.Open Data Catalogue. (n.d.). Retrieved September 27, 2020, from <a href="https://open.toronto.ca/catalogue/?search=crime" class="uri">https://open.toronto.ca/catalogue/?search=crime</a></p>
<p>2.A Complete Guide to Scatter Plots. (n.d.). Retrieved September 27, 2020, from <a href="https://chartio.com/learn/charts/what-is-a-scatter-plot/" class="uri">https://chartio.com/learn/charts/what-is-a-scatter-plot/</a></p>
</div>
